<?xml version="1.0"?>
<!DOCTYPE login [
<!ELEMENT login (username,password, email)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT email (#PCDATA)>
]>
<login>
	<id>1</id>
	<username>admin</username>
	<password>admin</password>
	<email>admin@gmail.com</email>
</login>